### ISSUE TITLE
flutter Android example报错跑步起来

### ISSUE THREAD

**Issue by c1avie** [JiangJuHong/FlutterTencentRtcPlugin#16]
2020-08-18 17:59:30.156 8800-8800/? W/NativeLoad: load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libliteavsdk.so" not found
2020-08-18 17:59:30.156 8800-8800/? W/NativeLoad: load library liteavsdk false
2020-08-18 17:59:30.156 8800-8800/? E/_plugin_exampl: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
2020-08-18 17:59:30.156 8800-8800/? D/AndroidRuntime: Shutting down VM
2020-08-18 17:59:30.157 8800-8800/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.huic.tencent_rtc_plugin_example, PID: 8800
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative(Native Method)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.<clinit>(TXCTraeJNI.java:26)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCheckTraeEngine(TXCTraeJNI.java:87)
        at com.tencent.liteav.audio.a.a(TXCAudioEngine.java:40)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:230)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:193)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:37)
        at top.huic.tencent_rtc_plugin.TencentRtcPlugin.<init>(TencentRtcPlugin.java:41)
        at top.huic.tencent_rtc_plugin.TencentRtcPlugin.onAttachedToEngine(TencentRtcPlugin.java:51)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
        at top.huic.tencent_rtc_plugin_example.MainActivity.configureFlutterEngine(MainActivity.java:11)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)

**Comment by JiangJuHong** [comment]
请使用 Android Studio 打开example/android 目录，build成功后即可运行

**Comment by c1avie** [comment]
看编译成功了，启动的时候报错。

2020-08-18 19:53:01.108 11506-11506/top.huic.tencent_rtc_plugin_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.huic.tencent_rtc_plugin_example, PID: 11506
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative() (tried Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative and Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeCacheClassForNative__)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCacheClassForNative(Native Method)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.<clinit>(TXCTraeJNI.java:26)
        at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeCheckTraeEngine(TXCTraeJNI.java:87)
        at com.tencent.liteav.audio.a.a(TXCAudioEngine.java:40)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:230)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:193)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:37)
        at top.huic.tencent_rtc_plugin.TencentRtcPlugin.<init>(TencentRtcPlugin.java:41)
        at top.huic.tencent_rtc_plugin.TencentRtcPlugin.onAttachedToEngine(TencentRtcPlugin.java:51)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
        at top.huic.tencent_rtc_plugin_example.MainActivity.configureFlutterEngine(MainActivity.java:11)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by c1avie** [comment]
用的是mac的安卓虚拟机

**Comment by JiangJuHong** [comment]
请使用真机运行 腾讯云 RTC 不支持 谷歌虚拟机架构

**Comment by c1avie** [comment]
mac的IOS虚拟机支持运行吗

**Comment by c1avie** [comment]
![image](https://user-images.githubusercontent.com/2912208/90590423-19016800-e213-11ea-9f03-7a80c0e27d7e.png)

报错信息如下

**Comment by JiangJuHong** [comment]
这个是项目错了，可根据提示进行 `pod install` 或 `pod update repo`

**Comment by c1avie** [comment]
pod install了，im 的ios demo可以正常跑起来。RTC的就报上面那个错误。你那边example demo可以正常跑吗

**Comment by JiangJuHong** [comment]
是的，我这边都能正常运行，你可以尝试一下`pod update repo`

**Comment by c1avie** [comment]
pod update repo也试了，不行。我另外一个同事跑rtc的demo，也是报一样的错误

**Comment by JiangJuHong** [comment]
非常抱歉，我发现了问题原因所在，是由于 example 中的 permisson_handler 使用了动态版本，导致自动升级为最新版后  `Permission.camera.request().isGranted` 方法失效，我现在已将它提交，更新后重新 `pub get`后则能正常使用

**Comment by c1avie** [comment]
我这边更新了也是报一样的错，方便加个qq吗，方便交流  429465251

**Comment by JiangJuHong** [comment]
更新了请重新运行 `pub get` 等待成功后再进行`pod install`，然后使用 xcode 运行

**Comment by c1avie** [comment]
我重新下载了，是按照这个流程的。你是用的真机还是虚拟机，我用的虚拟机不行

**Comment by JiangJuHong** [comment]
ios使用的模拟器，能够正常运行，android未尝试

**Comment by JiangJuHong** [comment]
请使用 xcode 打开  `FlutterTencentRtcPlugin/example/ios` 目录进行运行，非 `FlutterTencentRtcPlugin/ios`

**Comment by c1avie** [comment]
是这个目录的

**Comment by JiangJuHong** [comment]
可以尝试使用真机运行

**Comment by JiangJuHong** [comment]
我这里在模拟器和真机都没有问题

**Comment by c1avie** [comment]
cupertino_icons: 0.1.2
permission_handler: 5.0.1+1          你就更新了这两个配置是吧

**Comment by JiangJuHong** [comment]
是的，这也是导致这个问题的原因

**Comment by c1avie** [comment]
我让我同事那边试了下，更新后也是报的一样的错误。你这边下载一下最新的github代码试一下呢

**Comment by JiangJuHong** [comment]
我使用的就是最新代码

**Comment by JiangJuHong** [comment]
请先通过 谷歌、百度 等搜索引擎对错误提示进行搜索，查看是否有复现情况

**Comment by c1avie** [comment]
![image](https://user-images.githubusercontent.com/2912208/90625812-b88f1c80-e24c-11ea-9056-ab9555760e7e.png)

看这报错，应该是缺少某些类库。跟permisson_handler应该无关

**Comment by JiangJuHong** [comment]
可能我解决的并非你说的错误，但是我在我的几个设备上运行均运行成功，你可以尝试如下操作:
1. 新建一个Flutter项目
2. 引入插件
3. 尝试启动运行

**Comment by c1avie** [comment]
跟你确认下流程
下载完项目后
1.flutter pub get
2.cd example/ios
pod install
3.用xcode打开example/ios目录进行编译运行。
我们这边几个电脑按照这个流程操作都会报上面的错，帮忙确认下是否少配置了什么东西

**Comment by yhz199132** [comment]
> 可能我解决的并非你说的错误，但是我在我的几个设备上运行均运行成功，你可以尝试如下操作:
> 
> 1. 新建一个Flutter项目
> 2. 引入插件
> 3. 尝试启动运行

我这边跟他报了相同的问题，而且已经尝试新建项目也是同样错误.
当前环境 [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.48.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

cocoapods version:1.9.3

**Comment by yhz199132** [comment]
> 可能我解决的并非你说的错误，但是我在我的几个设备上运行均运行成功，你可以尝试如下操作:
> 
> 1. 新建一个Flutter项目
> 2. 引入插件
> 3. 尝试启动运行

或者你这边可以尝试清除一下cocoapods缓存，来复现一下问题。

**Comment by yhz199132** [comment]
> 可能我解决的并非你说的错误，但是我在我的几个设备上运行均运行成功，你可以尝试如下操作:
> 
> 1. 新建一个Flutter项目
> 2. 引入插件
> 3. 尝试启动运行

或者你这边可以尝试清除一下cocoapods缓存，来复现一下问题。

**Comment by hexingcheng** [comment]
我也遇到了，跑不起来啊老哥

**Comment by JiangJuHong** [comment]
我晚上回家后尝试一下

**Comment by c1avie** [comment]
找到原因了吗

**Comment by JiangJuHong** [comment]
清除 cocoapods 缓存后程序依旧可以在我的 iPhone 模拟器上运行，你们是否进行了 flutter clean 和 flutter build 操作。
请尝试如下内容: 

1. `flutter clean`
2. 运行(如果还不行则进行第3步)
3. `flutter build`
4. 运行


如果以上步骤不行，请提供您的设备信息以及完整的错误日志.

![image](https://user-images.githubusercontent.com/17740963/90711295-e8810300-e2d2-11ea-8108-ae9f7d8977f0.png)

**Comment by JiangJuHong** [comment]
补充说明： 如果以上步骤不行，请尝试
1. Xcode -> Product -> Clean Build Folder
2. run `flutter clean`
3. run `flutter build`
4. Xcode -> Product -> Build

**Comment by JiangJuHong** [comment]
如果依旧不行，请提供:
1. Xcode 版本信息
2. Flutter 版本信息
3. 错误完整日志
4. 开发机设备信息
5. 模拟器/测试机 设备信息

感谢支持

**Comment by c1avie** [comment]
1.xcode：Version 11.6 (11E708)
![image](https://user-images.githubusercontent.com/2912208/90714301-f1290780-e2d9-11ea-98ed-441c9d767ac3.png)

2.flutter版本信息
![image](https://user-images.githubusercontent.com/2912208/90714138-92fc2480-e2d9-11ea-8dfb-052474081a17.png)
3.flutter build失败日志
![image](https://user-images.githubusercontent.com/2912208/90714199-b32be380-e2d9-11ea-9b58-f26120354857.png)
xcode build失败日志：
![image](https://user-images.githubusercontent.com/2912208/90714385-233a6980-e2da-11ea-91b4-eaf74226985b.png)
4.mac版本
![image](https://user-images.githubusercontent.com/2912208/90714279-e7070900-e2d9-11ea-8d36-0a83cbabf030.png)
5.模拟器
![image](https://user-images.githubusercontent.com/2912208/90714422-33524900-e2da-11ea-8162-1662c50c6a99.png)

**Comment by JiangJuHong** [comment]
好的，我会进行排查

**Comment by JiangJuHong** [comment]
问题造成原因：由于腾讯云RTC升级了最新版本，插件内部使用的动态版本，导致自动升级，故引起运行错误
问题解决方案：固定腾讯云RTC版本

问题修复手册：
 1.  如果你使用demo，请更新后 在 `example/ios` 目录执行 `pod update TXLiteAVSDK_TRTC`
 2. 如果你使用插件，请将插件版本升级为 `0.1.12`

**Comment by c1avie** [comment]
demo已能正常运行，非常感谢。另外虚拟机上不能正常使用摄像头吗。
![image](https://user-images.githubusercontent.com/2912208/90725815-4f161900-e2f3-11ea-93dd-e7153b25b2c5.png)

**Comment by JiangJuHong** [comment]
iPhone模拟器貌似不支持调用摄像头，我在集成线上项目时都是通过真机进行调试的

**Comment by c1avie** [comment]
腾讯云rtc团队最近准备搭建官方flutter sdk，想问下你最近考虑腾讯的工作机会吗。

**Comment by JiangJuHong** [comment]
我主业是 JAVA后端开发，移动端和Flutter只是由于兴趣研究的比较多，应该不符合腾讯云的入职条件，感谢.

**Comment by c1avie** [comment]
我们这边也有java后端开发的岗位，云rtc团队是非常欢迎你的加入的，看你个人兴趣哈。如果不考虑换工作，后续期待跟你一起协同共建flutter sdk。

**Comment by JiangJuHong** [comment]
工作地点是在哪里呢？目前是个人在家办公状态，近期可能会找工作.

**Comment by c1avie** [comment]
工作地点主要在深圳，西安也有分部

**Comment by JiangJuHong** [comment]
抱歉，由于目前主要在成都发展，可能暂时没办法前往深圳，但是我非常期待与你们协同共建 flutter sdk.

**Comment by c1avie** [comment]
好的

**Comment by yhz199132** [comment]
> 问题造成原因：由于腾讯云RTC升级了最新版本，插件内部使用的动态版本，导致自动升级，故引起运行错误
> 问题解决方案：固定腾讯云RTC版本
> 
> 问题修复手册：
> 
> 1. 如果你使用demo，请更新后 在 `example/ios` 目录执行 `pod update TXLiteAVSDK_TRTC`
> 2. 如果你使用插件，请将插件版本升级为 `0.1.12`

非常感谢，新版本可以正常使用了。

**Comment by JiangJuHong** [comment]
如果没有其它问题  我将关闭此 issues，在需要时可以重新打开
