### ISSUE TITLE
多次进入房间会出现视频view显示异常

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#27]
![image](https://user-images.githubusercontent.com/70259290/94013362-8b4e0500-fddc-11ea-8dbb-7f31ef593280.png)
尝试多次进入房间、退出房间就会出现这个错误。

2020-09-23 20:36:02.551 5436-5436/top.huic.tencent_rtc_plugin_example E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.SecurityException: Neither user 10224 nor current process has android.permission.WAKE_LOCK.
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1263)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:942)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:344)
        at android.app.Presentation.show(Presentation.java:250)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:170)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7519)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1907)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1935)
        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4471)
        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2188)
        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2154)
2020-09-23 20:36:02.562 5436-5478/top.huic.tencent_rtc_plugin_example E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Neither user 10224 nor current process has android.permission.WAKE_LOCK., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:169:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:342:12)
    #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
    #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:746:11)
    #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1017:34)
    #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1001:14)
    #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
    #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:157:5)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:9)
    #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
    #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
    #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
    #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #38     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3226:14)
    #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #42     _RenderTheatre.perfor

**Comment by shop987** [comment]
安卓手机

![image](https://user-images.githubusercontent.com/70259290/94013677-fac3f480-fddc-11ea-9399-a0695cc0d106.png)

**Comment by shop987** [comment]
<uses-permission android:name="android.permission.WAKE_LOCK"/>   加了这个权限申请就好了

**Comment by shop987** [comment]
<uses-permission android:name="android.permission.WAKE_LOCK"/>

**Comment by shop987** [comment]
![image](https://user-images.githubusercontent.com/70259290/94094975-5761f680-fe53-11ea-8809-f3191305193b.png)
